export default [
  'HTML5',
  'JavaScript',
  'Usability engineering',
  'User-centred design',
  'User journey',
  'Lean UX',
  'Iterative design',
  'Principles Over Standards',
  'Accessibility First',
  'Continuous integration',
  'Test-driven development',
  'Pair programming',
  'Experience design',
  'Module bundlers',
  'React',
  'Redux',
  'Unit Testing',
  'ES2017',
  'Forward thinking',
  'Leadership',
  'Mentoring',
  'Internet of things',
  'Async functions'
]